[workspace]

members = [
    "open_tab_entities",
    "open_tab_server",
    "open_tab_app//src-tauri",
    "open_tab_app_backend",
    "open_tab_macros",
    "open_tab_reports",
]

workspace.resolver = "2"